INSERT INTO data (name, category) VALUES ('worn axe', 'product');
INSERT INTO data (name, category) VALUES ('Toilet Bowl Cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Sponges', 'product');
INSERT INTO data (name, category) VALUES ('Dishwasher Pods', 'product');
INSERT INTO data (name, category) VALUES ('Wipes', 'product');
INSERT INTO data (name, category) VALUES ('Aluminum Foil', 'product');
INSERT INTO data (name, category) VALUES ('Sandwich Bags', 'product');
INSERT INTO data (name, category) VALUES ('Dryer Sheets', 'product');
INSERT INTO data (name, category) VALUES ('Fabric Softener', 'product');
INSERT INTO data (name, category) VALUES ('Trash Bags', 'product');
INSERT INTO data (name, category) VALUES ('Napkins', 'product');
INSERT INTO data (name, category) VALUES ('Tissues', 'product');
INSERT INTO data (name, category) VALUES ('Dish Soap', 'product');
INSERT INTO data (name, category) VALUES ('Paper Towels', 'product');
INSERT INTO data (name, category) VALUES ('Toilet Paper', 'product');
INSERT INTO data (name, category) VALUES ('Gardening gloves', 'product');
INSERT INTO data (name, category) VALUES ('Kneeling pad', 'product');
INSERT INTO data (name, category) VALUES ('Weather-resistant watering can', 'product');
INSERT INTO data (name, category) VALUES ('Hose and appropriate spray nozzles', 'product');
INSERT INTO data (name, category) VALUES ('Pruning shears', 'product');
INSERT INTO data (name, category) VALUES ('Trowel for digging', 'product');
INSERT INTO data (name, category) VALUES ('Cultivator for loosening and aerating soil', 'product');
INSERT INTO data (name, category) VALUES ('Gardening rake', 'product');
INSERT INTO data (name, category) VALUES ('Spade for digging', 'product');
INSERT INTO data (name, category) VALUES ('Pitchfork to remove stones', 'product');
INSERT INTO data (name, category) VALUES ('Wheelbarrow', 'product');
INSERT INTO data (name, category) VALUES ('Gardening cart', 'product');
INSERT INTO data (name, category) VALUES ('Toolbox', 'product');
INSERT INTO data (name, category) VALUES ('Hammock', 'product');
INSERT INTO data (name, category) VALUES ('Lawn chairs', 'product');
INSERT INTO data (name, category) VALUES ('Picnic table', 'product');
INSERT INTO data (name, category) VALUES ('Badminton or volleyball set', 'product');
INSERT INTO data (name, category) VALUES ('Patio umbrella', 'product');
INSERT INTO data (name, category) VALUES ('Sun tent', 'product');
INSERT INTO data (name, category) VALUES ('Bluetooth speakers', 'product');
INSERT INTO data (name, category) VALUES ('Citronella candles', 'product');
INSERT INTO data (name, category) VALUES ('Fire pit', 'product');
INSERT INTO data (name, category) VALUES ('Sprinkler', 'product');
INSERT INTO data (name, category) VALUES ('Cooler', 'product');
INSERT INTO data (name, category) VALUES ('Bug spray', 'product');
INSERT INTO data (name, category) VALUES ('Sunscreen', 'product');
INSERT INTO data (name, category) VALUES ('Grill', 'product');
INSERT INTO data (name, category) VALUES ('Charcoal', 'product');
INSERT INTO data (name, category) VALUES ('Tongs', 'product');
INSERT INTO data (name, category) VALUES ('Lighter', 'product');
INSERT INTO data (name, category) VALUES ('Tablecloth', 'product');
INSERT INTO data (name, category) VALUES ('Smores sticks', 'product');
INSERT INTO data (name, category) VALUES ('Wood', 'product');
INSERT INTO data (name, category) VALUES ('Plastic cups and cutlery', 'product');
INSERT INTO data (name, category) VALUES ('Straws', 'product');
INSERT INTO data (name, category) VALUES ('Blender or margarita maker', 'product');
INSERT INTO data (name, category) VALUES ('Fun cocktail glasses', 'product');
INSERT INTO data (name, category) VALUES ('Serving trays', 'product');
INSERT INTO data (name, category) VALUES ('Lemonade pitcher', 'product');
INSERT INTO data (name, category) VALUES ('Water dispenser', 'product');
INSERT INTO data (name, category) VALUES ('Birdfeeder and feed', 'product');
INSERT INTO data (name, category) VALUES ('Binoculars', 'product');
INSERT INTO data (name, category) VALUES ('Cleaning caddy', 'product');
INSERT INTO data (name, category) VALUES ('Plastic gloves', 'product');
INSERT INTO data (name, category) VALUES ('Paper towels', 'product');
INSERT INTO data (name, category) VALUES ('Scrubber', 'product');
INSERT INTO data (name, category) VALUES ('Mop', 'product');
INSERT INTO data (name, category) VALUES ('Bucket', 'product');
INSERT INTO data (name, category) VALUES ('Broom', 'product');
INSERT INTO data (name, category) VALUES ('Dustpan', 'product');
INSERT INTO data (name, category) VALUES ('Duster', 'product');
INSERT INTO data (name, category) VALUES ('Dusting mitt', 'product');
INSERT INTO data (name, category) VALUES ('Microfiber clothes', 'product');
INSERT INTO data (name, category) VALUES ('Garbage bags', 'product');
INSERT INTO data (name, category) VALUES ('Scrub brush', 'product');
INSERT INTO data (name, category) VALUES ('Blind cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Oven cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Multi-surface cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Dust spray', 'product');
INSERT INTO data (name, category) VALUES ('Wood cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Disinfecting spray', 'product');
INSERT INTO data (name, category) VALUES ('Toilet bowl cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Glass cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Vacuum', 'product');
INSERT INTO data (name, category) VALUES ('Distilled white vinegar', 'product');
INSERT INTO data (name, category) VALUES ('Ceramic cooktop cleanser', 'product');
INSERT INTO data (name, category) VALUES ('Toilet brush', 'product');
INSERT INTO data (name, category) VALUES ('Dish soap', 'product');
INSERT INTO data (name, category) VALUES ('Scented room spray', 'product');
INSERT INTO data (name, category) VALUES ('Sofa Set or Couch', 'product');
INSERT INTO data (name, category) VALUES ('Coffee Table', 'product');
INSERT INTO data (name, category) VALUES ('Entertainment Unit', 'product');
INSERT INTO data (name, category) VALUES ('Side Tables', 'product');
INSERT INTO data (name, category) VALUES ('Bookcase or Book Stand', 'product');
INSERT INTO data (name, category) VALUES ('Desks', 'product');
INSERT INTO data (name, category) VALUES ('Computer Table', 'product');
INSERT INTO data (name, category) VALUES ('Music Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('Table Lamps', 'product');
INSERT INTO data (name, category) VALUES ('Ceiling Hangings & Lights', 'product');
INSERT INTO data (name, category) VALUES ('Throw Pillows', 'product');
INSERT INTO data (name, category) VALUES ('Home Décor Items', 'product');
INSERT INTO data (name, category) VALUES ('Sofa Throws', 'product');
INSERT INTO data (name, category) VALUES ('Wall Decor & Art', 'product');
INSERT INTO data (name, category) VALUES ('Curtain Rods', 'product');
INSERT INTO data (name, category) VALUES ('Television', 'product');
INSERT INTO data (name, category) VALUES ('Music System', 'product');
INSERT INTO data (name, category) VALUES ('Indoor Plants & Vase', 'product');
INSERT INTO data (name, category) VALUES ('Wall Mounted Shelves', 'product');
INSERT INTO data (name, category) VALUES ('Lighting', 'product');
INSERT INTO data (name, category) VALUES ('Sentimental Photos', 'product');
INSERT INTO data (name, category) VALUES ('CarpetBench', 'product');
INSERT INTO data (name, category) VALUES ('Storage Unit', 'product');
INSERT INTO data (name, category) VALUES ('Armchairs', 'product');
INSERT INTO data (name, category) VALUES ('Cabinets', 'product');
INSERT INTO data (name, category) VALUES ('Planters', 'product');
INSERT INTO data (name, category) VALUES ('Speakers', 'product');
INSERT INTO data (name, category) VALUES ('Piano', 'product');
INSERT INTO data (name, category) VALUES ('Rocking Chair', 'product');
INSERT INTO data (name, category) VALUES ('Refrigerator', 'product');
INSERT INTO data (name, category) VALUES ('AC', 'product');
INSERT INTO data (name, category) VALUES ('Fan', 'product');
INSERT INTO data (name, category) VALUES ('CD Player', 'product');
INSERT INTO data (name, category) VALUES ('Tables', 'product');
INSERT INTO data (name, category) VALUES ('Wall Clock', 'product');
INSERT INTO data (name, category) VALUES ('Table Clock', 'product');
INSERT INTO data (name, category) VALUES ('Trivet / Teapot coaster', 'product');
INSERT INTO data (name, category) VALUES ('Dining Table', 'product');
INSERT INTO data (name, category) VALUES ('Dinging Chairs', 'product');
INSERT INTO data (name, category) VALUES ('Host Chairs', 'product');
INSERT INTO data (name, category) VALUES ('Side Chairs', 'product');
INSERT INTO data (name, category) VALUES ('CabinetHutch', 'product');
INSERT INTO data (name, category) VALUES ('Ceiling Fans', 'product');
INSERT INTO data (name, category) VALUES ('Ceiling Hangings & Decors', 'product');
INSERT INTO data (name, category) VALUES ('Tea Cart', 'product');
INSERT INTO data (name, category) VALUES ('Dining ', 'product');
INSERT INTO data (name, category) VALUES ('Room ', 'product');
INSERT INTO data (name, category) VALUES ('Feng Shui ItemsWall Décors', 'product');
INSERT INTO data (name, category) VALUES ('Linens', 'product');
INSERT INTO data (name, category) VALUES ('Flower Vase', 'product');
INSERT INTO data (name, category) VALUES ('Drapes', 'product');
INSERT INTO data (name, category) VALUES ('Corner Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('Display Cabinets', 'product');
INSERT INTO data (name, category) VALUES ('Table leaf bags', 'product');
INSERT INTO data (name, category) VALUES ('Service Table', 'product');
INSERT INTO data (name, category) VALUES ('Bench', 'product');
INSERT INTO data (name, category) VALUES ('Sideboard', 'product');
INSERT INTO data (name, category) VALUES ('Artworks', 'product');
INSERT INTO data (name, category) VALUES ('Paintings ', 'product');
INSERT INTO data (name, category) VALUES ('Fames', 'product');
INSERT INTO data (name, category) VALUES ('Vases', 'product');
INSERT INTO data (name, category) VALUES ('Urns ', 'product');
INSERT INTO data (name, category) VALUES ('Pitchers', 'product');
INSERT INTO data (name, category) VALUES ('Baskets', 'product');
INSERT INTO data (name, category) VALUES ('boxes', 'product');
INSERT INTO data (name, category) VALUES ('Dinnerware', 'product');
INSERT INTO data (name, category) VALUES ('Crystal glassware', 'product');
INSERT INTO data (name, category) VALUES ('Silverware', 'product');
INSERT INTO data (name, category) VALUES ('Silverware storage', 'product');
INSERT INTO data (name, category) VALUES ('Trays', 'product');
INSERT INTO data (name, category) VALUES ('Serving platters', 'product');
INSERT INTO data (name, category) VALUES ('Trivet', 'product');
INSERT INTO data (name, category) VALUES ('Teapot ', 'product');
INSERT INTO data (name, category) VALUES ('coaster', 'product');
INSERT INTO data (name, category) VALUES ('Carpets', 'product');
INSERT INTO data (name, category) VALUES ('Gas Stove', 'product');
INSERT INTO data (name, category) VALUES ('Gas Cylinder', 'product');
INSERT INTO data (name, category) VALUES ('Dishwasher', 'product');
INSERT INTO data (name, category) VALUES ('Oven', 'product');
INSERT INTO data (name, category) VALUES ('Griller', 'product');
INSERT INTO data (name, category) VALUES ('Microwave Oven', 'product');
INSERT INTO data (name, category) VALUES ('Freezer', 'product');
INSERT INTO data (name, category) VALUES ('Stool', 'product');
INSERT INTO data (name, category) VALUES ('Induction Top', 'product');
INSERT INTO data (name, category) VALUES ('Chef’s knife', 'product');
INSERT INTO data (name, category) VALUES ('Storage Containers', 'product');
INSERT INTO data (name, category) VALUES ('Chopping', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen towels', 'product');
INSERT INTO data (name, category) VALUES ('Can/Bottle Opener', 'product');
INSERT INTO data (name, category) VALUES ('Mixing Bowls', 'product');
INSERT INTO data (name, category) VALUES ('Juicer', 'product');
INSERT INTO data (name, category) VALUES ('Mixer Grinder', 'product');
INSERT INTO data (name, category) VALUES ('BlenderCrockery Set', 'product');
INSERT INTO data (name, category) VALUES ('Glasses', 'product');
INSERT INTO data (name, category) VALUES ('Cups & Saucers', 'product');
INSERT INTO data (name, category) VALUES ('Coffee Mugs', 'product');
INSERT INTO data (name, category) VALUES ('Measuring Cups', 'product');
INSERT INTO data (name, category) VALUES ('Measuring Spoons', 'product');
INSERT INTO data (name, category) VALUES ('Vegetable Peeler', 'product');
INSERT INTO data (name, category) VALUES ('Colander', 'product');
INSERT INTO data (name, category) VALUES ('Potato Masher', 'product');
INSERT INTO data (name, category) VALUES ('Grater', 'product');
INSERT INTO data (name, category) VALUES ('Salad Spinner', 'product');
INSERT INTO data (name, category) VALUES ('Citrus Juicer', 'product');
INSERT INTO data (name, category) VALUES ('Dish Rack', 'product');
INSERT INTO data (name, category) VALUES ('Dish Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('Ladle', 'product');
INSERT INTO data (name, category) VALUES ('Spoons of Different Sizes', 'product');
INSERT INTO data (name, category) VALUES ('Forks', 'product');
INSERT INTO data (name, category) VALUES ('Metal Tongs', 'product');
INSERT INTO data (name, category) VALUES ('Pots & Utensils', 'product');
INSERT INTO data (name, category) VALUES ('Single Bed', 'product');
INSERT INTO data (name, category) VALUES ('Double Bed', 'product');
INSERT INTO data (name, category) VALUES ('King Size Bed', 'product');
INSERT INTO data (name, category) VALUES ('Cot', 'product');
INSERT INTO data (name, category) VALUES ('Couch', 'product');
INSERT INTO data (name, category) VALUES ('Sofa', 'product');
INSERT INTO data (name, category) VALUES ('Bunk Bed', 'product');
INSERT INTO data (name, category) VALUES ('Diwan Bed', 'product');
INSERT INTO data (name, category) VALUES ('Chest of Drawer', 'product');
INSERT INTO data (name, category) VALUES ('CabinetChairs', 'product');
INSERT INTO data (name, category) VALUES ('LinensCarpets', 'product');
INSERT INTO data (name, category) VALUES ('CurtainCurtain ', 'product');
INSERT INTO data (name, category) VALUES ('Rods', 'product');
INSERT INTO data (name, category) VALUES ('Pillows', 'product');
INSERT INTO data (name, category) VALUES ('Mattress', 'product');
INSERT INTO data (name, category) VALUES ('Lampshades', 'product');
INSERT INTO data (name, category) VALUES ('Night Table', 'product');
INSERT INTO data (name, category) VALUES ('Alarm Clock', 'product');
INSERT INTO data (name, category) VALUES ('Wastepaper Bin', 'product');
INSERT INTO data (name, category) VALUES ('Hangers', 'product');
INSERT INTO data (name, category) VALUES ('Wardrobe', 'product');
INSERT INTO data (name, category) VALUES ('Office Chair', 'product');
INSERT INTO data (name, category) VALUES ('Dresser', 'product');
INSERT INTO data (name, category) VALUES ('MirrorWall Décors', 'product');
INSERT INTO data (name, category) VALUES ('Flash Light / Torch', 'product');
INSERT INTO data (name, category) VALUES ('TV', 'product');
INSERT INTO data (name, category) VALUES ('Laundry Basket', 'product');
INSERT INTO data (name, category) VALUES ('Suitcase', 'product');
INSERT INTO data (name, category) VALUES ('PC/Laptop', 'product');
INSERT INTO data (name, category) VALUES ('Nightstand/Bedside ', 'product');
INSERT INTO data (name, category) VALUES ('Table', 'product');
INSERT INTO data (name, category) VALUES ('Bed End ', 'product');
INSERT INTO data (name, category) VALUES ('Kid’s Beds', 'product');
INSERT INTO data (name, category) VALUES ('Toddler Beds', 'product');
INSERT INTO data (name, category) VALUES ('Kids’ Tables', 'product');
INSERT INTO data (name, category) VALUES ('Kids’ Storage', 'product');
INSERT INTO data (name, category) VALUES ('Tween Beds', 'product');
INSERT INTO data (name, category) VALUES ('Baby Carriage', 'product');
INSERT INTO data (name, category) VALUES ('Child Desks', 'product');
INSERT INTO data (name, category) VALUES ('Child Chair', 'product');
INSERT INTO data (name, category) VALUES ('Toys & Games', 'product');
INSERT INTO data (name, category) VALUES ('Stroller', 'product');
INSERT INTO data (name, category) VALUES ('Blankets', 'product');
INSERT INTO data (name, category) VALUES ('quilts', 'product');
INSERT INTO data (name, category) VALUES ('Comforter', 'product');
INSERT INTO data (name, category) VALUES ('bedspread', 'product');
INSERT INTO data (name, category) VALUES ('Pillows & Cushions', 'product');
INSERT INTO data (name, category) VALUES ('Lamps', 'product');
INSERT INTO data (name, category) VALUES ('DVD Players with Kids Videos', 'product');
INSERT INTO data (name, category) VALUES ('Bookshelves', 'product');
INSERT INTO data (name, category) VALUES ('Photos', 'product');
INSERT INTO data (name, category) VALUES ('Frames', 'product');
INSERT INTO data (name, category) VALUES ('Posters', 'product');
INSERT INTO data (name, category) VALUES ('Decorative Objects', 'product');
INSERT INTO data (name, category) VALUES ('Backpack Bags', 'product');
INSERT INTO data (name, category) VALUES ('Nightlight', 'product');
INSERT INTO data (name, category) VALUES ('Torch & Flashlight', 'product');
INSERT INTO data (name, category) VALUES ('Ceiling Fan', 'product');
INSERT INTO data (name, category) VALUES ('Miscellaneous Items', 'product');
INSERT INTO data (name, category) VALUES ('Desk/Table', 'product');
INSERT INTO data (name, category) VALUES ('Computer', 'product');
INSERT INTO data (name, category) VALUES ('Laptop', 'product');
INSERT INTO data (name, category) VALUES ('Computer Desk', 'product');
INSERT INTO data (name, category) VALUES ('Xerox Machine', 'product');
INSERT INTO data (name, category) VALUES ('PrinterBook Shelves', 'product');
INSERT INTO data (name, category) VALUES ('Mini Library', 'product');
INSERT INTO data (name, category) VALUES ('BooksCabinets', 'product');
INSERT INTO data (name, category) VALUES ('Desk Lamps', 'product');
INSERT INTO data (name, category) VALUES ('Lightings', 'product');
INSERT INTO data (name, category) VALUES ('Armoire desk', 'product');
INSERT INTO data (name, category) VALUES ('Telephone', 'product');
INSERT INTO data (name, category) VALUES ('Fax Machine', 'product');
INSERT INTO data (name, category) VALUES ('Filing Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('Executive Chair', 'product');
INSERT INTO data (name, category) VALUES ('RO Machine', 'product');
INSERT INTO data (name, category) VALUES ('Clothes Dryer', 'product');
INSERT INTO data (name, category) VALUES ('Washing Machine', 'product');
INSERT INTO data (name, category) VALUES ('Drying Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('Water Heater', 'product');
INSERT INTO data (name, category) VALUES ('Geyser', 'product');
INSERT INTO data (name, category) VALUES ('Air Conditioner', 'product');
INSERT INTO data (name, category) VALUES ('Air Cooler', 'product');
INSERT INTO data (name, category) VALUES ('Electric Heater', 'product');
INSERT INTO data (name, category) VALUES ('Coffee Maker', 'product');
INSERT INTO data (name, category) VALUES ('Blender', 'product');
INSERT INTO data (name, category) VALUES ('Mixer', 'product');
INSERT INTO data (name, category) VALUES ('Hair Dryer', 'product');
INSERT INTO data (name, category) VALUES ('Vacuum Cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Iron', 'product');
INSERT INTO data (name, category) VALUES ('Ironing Board', 'product');
INSERT INTO data (name, category) VALUES ('Utility ', 'product');
INSERT INTO data (name, category) VALUES ('CabinetAir Purifier', 'product');
INSERT INTO data (name, category) VALUES ('Sewing Machine', 'product');
INSERT INTO data (name, category) VALUES ('Gym Exercise Equipment', 'product');
INSERT INTO data (name, category) VALUES ('Ladder', 'product');
INSERT INTO data (name, category) VALUES ('Metal Almirah', 'product');
INSERT INTO data (name, category) VALUES ('Car Table', 'product');
INSERT INTO data (name, category) VALUES ('Waste Basket', 'product');
INSERT INTO data (name, category) VALUES ('Baby items', 'product');
INSERT INTO data (name, category) VALUES ('BureausDecorative Items', 'product');
INSERT INTO data (name, category) VALUES ('Sectionals', 'product');
INSERT INTO data (name, category) VALUES ('Sofa Beds', 'product');
INSERT INTO data (name, category) VALUES ('Lawn Chairs', 'product');
INSERT INTO data (name, category) VALUES ('Hand Tools', 'product');
INSERT INTO data (name, category) VALUES ('Medical Equipment', 'product');
INSERT INTO data (name, category) VALUES ('Toaster Oven', 'product');
INSERT INTO data (name, category) VALUES ('Umbrellas', 'product');
INSERT INTO data (name, category) VALUES ('Bathroom Mirrors', 'product');
INSERT INTO data (name, category) VALUES ('Bathroom Cabinet', 'product');
INSERT INTO data (name, category) VALUES ('DustbinBread bin', 'product');
INSERT INTO data (name, category) VALUES ('Paper towel holder', 'product');
INSERT INTO data (name, category) VALUES ('Gas Oven', 'product');
INSERT INTO data (name, category) VALUES ('Induction Cooktop', 'product');
INSERT INTO data (name, category) VALUES ('Mixer & Grinder', 'product');
INSERT INTO data (name, category) VALUES ('Hand Blender', 'product');
INSERT INTO data (name, category) VALUES ('Bread Pin', 'product');
INSERT INTO data (name, category) VALUES ('Electric Toaster', 'product');
INSERT INTO data (name, category) VALUES ('Electric Kettle', 'product');
INSERT INTO data (name, category) VALUES ('Dustbin', 'product');
INSERT INTO data (name, category) VALUES ('Paper Towel Holder', 'product');
INSERT INTO data (name, category) VALUES ('Exhaust Fan or Kitchen Chimney', 'product');
INSERT INTO data (name, category) VALUES ('Cooking Utensils and Accessories', 'product');
INSERT INTO data (name, category) VALUES ('Chef’s Knife', 'product');
INSERT INTO data (name, category) VALUES ('Cutting/Chopping Board', 'product');
INSERT INTO data (name, category) VALUES ('Spatula', 'product');
INSERT INTO data (name, category) VALUES ('Fry Pan', 'product');
INSERT INTO data (name, category) VALUES ('Sauté Pan', 'product');
INSERT INTO data (name, category) VALUES ('Kadahi', 'product');
INSERT INTO data (name, category) VALUES ('Saucepan', 'product');
INSERT INTO data (name, category) VALUES ('Small Pots', 'product');
INSERT INTO data (name, category) VALUES ('Large Pots', 'product');
INSERT INTO data (name, category) VALUES ('Baking Tray', 'product');
INSERT INTO data (name, category) VALUES ('Jug', 'product');
INSERT INTO data (name, category) VALUES ('Condiment holders', 'product');
INSERT INTO data (name, category) VALUES ('Stockpot', 'product');
INSERT INTO data (name, category) VALUES ('Slotted Spoon', 'product');
INSERT INTO data (name, category) VALUES ('Oven Mitts', 'product');
INSERT INTO data (name, category) VALUES ('Food Storage Containers', 'product');
INSERT INTO data (name, category) VALUES ('Heavy Sponges', 'product');
INSERT INTO data (name, category) VALUES ('Ice Cube Tray', 'product');
INSERT INTO data (name, category) VALUES ('Small Trash Bags', 'product');
INSERT INTO data (name, category) VALUES ('Large Trash Bags', 'product');
INSERT INTO data (name, category) VALUES ('Items for eating and drinking purposes', 'product');
INSERT INTO data (name, category) VALUES ('Serving Dishes', 'product');
INSERT INTO data (name, category) VALUES ('Knives and Forks', 'product');
INSERT INTO data (name, category) VALUES ('Spoons ', 'product');
INSERT INTO data (name, category) VALUES ('tea spoons', 'product');
INSERT INTO data (name, category) VALUES ('soup spoons', 'product');
INSERT INTO data (name, category) VALUES ('table spoons', 'product');
INSERT INTO data (name, category) VALUES ('Bowls', 'product');
INSERT INTO data (name, category) VALUES ('soup bowl', 'product');
INSERT INTO data (name, category) VALUES ('fruit bow', 'product');
INSERT INTO data (name, category) VALUES ('salad bow', 'product');
INSERT INTO data (name, category) VALUES ('chutney bowl', 'product');
INSERT INTO data (name, category) VALUES ('Drinking Glasses', 'product');
INSERT INTO data (name, category) VALUES ('Plates ', 'product');
INSERT INTO data (name, category) VALUES ('dinner plates', 'product');
INSERT INTO data (name, category) VALUES ('serving plates', 'product');
INSERT INTO data (name, category) VALUES ('side plates', 'product');
INSERT INTO data (name, category) VALUES ('Items to clean kitchen', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen Sponge', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen Scrubber', 'product');
INSERT INTO data (name, category) VALUES ('Wiping Clothes', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen Towels', 'product');
INSERT INTO data (name, category) VALUES ('Washing Liquid or Bar', 'product');
INSERT INTO data (name, category) VALUES ('General Disinfectant', 'product');
INSERT INTO data (name, category) VALUES ('Cleaning Sprays', 'product');
INSERT INTO data (name, category) VALUES ('Bathroom Sink', 'product');
INSERT INTO data (name, category) VALUES ('Shower', 'product');
INSERT INTO data (name, category) VALUES ('Shower Curtain', 'product');
INSERT INTO data (name, category) VALUES ('Towel Rack', 'product');
INSERT INTO data (name, category) VALUES ('Hand Towels', 'product');
INSERT INTO data (name, category) VALUES ('Bath Towels', 'product');
INSERT INTO data (name, category) VALUES ('Face Cloth', 'product');
INSERT INTO data (name, category) VALUES ('Bath Tub', 'product');
INSERT INTO data (name, category) VALUES ('Soap Dish', 'product');
INSERT INTO data (name, category) VALUES ('Air Freshener', 'product');
INSERT INTO data (name, category) VALUES ('Bathroom Mat', 'product');
INSERT INTO data (name, category) VALUES ('Plunger', 'product');
INSERT INTO data (name, category) VALUES ('Toilet Brush', 'product');
INSERT INTO data (name, category) VALUES ('Toilet Cleaning Supplies', 'product');
INSERT INTO data (name, category) VALUES ('Toilet Roll with Holder', 'product');
INSERT INTO data (name, category) VALUES ('Antiseptic creams', 'product');
INSERT INTO data (name, category) VALUES ('Adhesive bandages', 'product');
INSERT INTO data (name, category) VALUES ('Tweezers', 'product');
INSERT INTO data (name, category) VALUES ('Tape and sterile gauze', 'product');
INSERT INTO data (name, category) VALUES ('Muscle pain spray or tube', 'product');
INSERT INTO data (name, category) VALUES ('Thermometer and medicine for fever', 'product');
INSERT INTO data (name, category) VALUES ('Allergy medicine', 'product');
INSERT INTO data (name, category) VALUES ('Latex Gloves', 'product');
INSERT INTO data (name, category) VALUES ('Analgesic – pain killers', 'product');
INSERT INTO data (name, category) VALUES ('Crepe bandages', 'product');
INSERT INTO data (name, category) VALUES ('Antiseptic liquid such as Dettol', 'product');
INSERT INTO data (name, category) VALUES ('Small scissors', 'product');
INSERT INTO data (name, category) VALUES ('Antibiotic ointments', 'product');
INSERT INTO data (name, category) VALUES ('Alcohol-free cleansing wipes', 'product');
INSERT INTO data (name, category) VALUES ('Flashlight / Torch', 'product');
INSERT INTO data (name, category) VALUES ('Smoke Alarm', 'product');
INSERT INTO data (name, category) VALUES ('Fire Extinguisher', 'product');
INSERT INTO data (name, category) VALUES ('Fire Blanket', 'product');
INSERT INTO data (name, category) VALUES ('First Aid Box', 'product');
INSERT INTO data (name, category) VALUES ('Extra Batteries', 'product');
INSERT INTO data (name, category) VALUES ('Drill Machine', 'product');
INSERT INTO data (name, category) VALUES ('Measuring Tape', 'product');
INSERT INTO data (name, category) VALUES ('Heavy Duty Packaging Tape', 'product');
INSERT INTO data (name, category) VALUES ('Step Ladder', 'product');
INSERT INTO data (name, category) VALUES ('Screws & Screwdrivers', 'product');
INSERT INTO data (name, category) VALUES ('Electricity Taster', 'product');
INSERT INTO data (name, category) VALUES ('Wire Cutter', 'product');
INSERT INTO data (name, category) VALUES ('Hammer', 'product');
INSERT INTO data (name, category) VALUES ('Spare Light Bulbs', 'product');
INSERT INTO data (name, category) VALUES ('Batteries', 'product');
INSERT INTO data (name, category) VALUES ('Wrenches', 'product');
INSERT INTO data (name, category) VALUES ('Laundry Tub', 'product');
INSERT INTO data (name, category) VALUES ('Clothes Horse', 'product');
INSERT INTO data (name, category) VALUES ('Water Filter Machine', 'product');
INSERT INTO data (name, category) VALUES ('Headboard', 'product');
INSERT INTO data (name, category) VALUES ('Dining Tables & Chairs', 'product');
INSERT INTO data (name, category) VALUES ('Storage Cabinets', 'product');
INSERT INTO data (name, category) VALUES ('Decorative Items', 'product');
INSERT INTO data (name, category) VALUES ('Bedside Tables', 'product');
INSERT INTO data (name, category) VALUES ('Luxury Items', 'product');
INSERT INTO data (name, category) VALUES ('abaya', 'product');
INSERT INTO data (name, category) VALUES ('anorak', 'product');
INSERT INTO data (name, category) VALUES ('apparel', 'product');
INSERT INTO data (name, category) VALUES ('apron', 'product');
INSERT INTO data (name, category) VALUES ('ascot ', 'product');
INSERT INTO data (name, category) VALUES ('tie ', 'product');
INSERT INTO data (name, category) VALUES ('attire', 'product');
INSERT INTO data (name, category) VALUES ('balaclava', 'product');
INSERT INTO data (name, category) VALUES ('ball gown', 'product');
INSERT INTO data (name, category) VALUES ('bandanna', 'product');
INSERT INTO data (name, category) VALUES ('bathing suit', 'product');
INSERT INTO data (name, category) VALUES ('battledress', 'product');
INSERT INTO data (name, category) VALUES ('beanie', 'product');
INSERT INTO data (name, category) VALUES ('bedclothes', 'product');
INSERT INTO data (name, category) VALUES ('belt', 'product');
INSERT INTO data (name, category) VALUES ('Bermuda shorts', 'product');
INSERT INTO data (name, category) VALUES ('bib', 'product');
INSERT INTO data (name, category) VALUES ('bikini', 'product');
INSERT INTO data (name, category) VALUES ('blazer', 'product');
INSERT INTO data (name, category) VALUES ('bloomers', 'product');
INSERT INTO data (name, category) VALUES ('blouse', 'product');
INSERT INTO data (name, category) VALUES ('boabonnet', 'product');
INSERT INTO data (name, category) VALUES ('bow', 'product');
INSERT INTO data (name, category) VALUES ('bow tie', 'product');
INSERT INTO data (name, category) VALUES ('boxer shorts', 'product');
INSERT INTO data (name, category) VALUES ('boxers', 'product');
INSERT INTO data (name, category) VALUES ('bra', 'product');
INSERT INTO data (name, category) VALUES ('bracelet', 'product');
INSERT INTO data (name, category) VALUES ('brassiere', 'product');
INSERT INTO data (name, category) VALUES ('breeches', 'product');
INSERT INTO data (name, category) VALUES ('briefs', 'product');
INSERT INTO data (name, category) VALUES ('buckle', 'product');
INSERT INTO data (name, category) VALUES ('button', 'product');
INSERT INTO data (name, category) VALUES ('button-down shirt', 'product');
INSERT INTO data (name, category) VALUES ('caftan', 'product');
INSERT INTO data (name, category) VALUES ('camisole', 'product');
INSERT INTO data (name, category) VALUES ('camouflage', 'product');
INSERT INTO data (name, category) VALUES ('cap', 'product');
INSERT INTO data (name, category) VALUES ('cap and gown', 'product');
INSERT INTO data (name, category) VALUES ('cape', 'product');
INSERT INTO data (name, category) VALUES ('capris', 'product');
INSERT INTO data (name, category) VALUES ('cardigan', 'product');
INSERT INTO data (name, category) VALUES ('chemise', 'product');
INSERT INTO data (name, category) VALUES ('cloak', 'product');
INSERT INTO data (name, category) VALUES ('clogs', 'product');
INSERT INTO data (name, category) VALUES ('clothes', 'product');
INSERT INTO data (name, category) VALUES ('clothing', 'product');
INSERT INTO data (name, category) VALUES ('coatcollar', 'product');
INSERT INTO data (name, category) VALUES ('corset', 'product');
INSERT INTO data (name, category) VALUES ('costume', 'product');
INSERT INTO data (name, category) VALUES ('coveralls', 'product');
INSERT INTO data (name, category) VALUES ('cowboy hat', 'product');
INSERT INTO data (name, category) VALUES ('cravat', 'product');
INSERT INTO data (name, category) VALUES ('cuff', 'product');
INSERT INTO data (name, category) VALUES ('cuff links', 'product');
INSERT INTO data (name, category) VALUES ('cummerbund', 'product');
INSERT INTO data (name, category) VALUES ('dashiki', 'product');
INSERT INTO data (name, category) VALUES ('diaper', 'product');
INSERT INTO data (name, category) VALUES ('dinner jacket', 'product');
INSERT INTO data (name, category) VALUES ('dirndl', 'product');
INSERT INTO data (name, category) VALUES ('drawers', 'product');
INSERT INTO data (name, category) VALUES ('dress', 'product');
INSERT INTO data (name, category) VALUES ('dress shirt', 'product');
INSERT INTO data (name, category) VALUES ('duds', 'product');
INSERT INTO data (name, category) VALUES ('dungarees', 'product');
INSERT INTO data (name, category) VALUES ('earmuffs', 'product');
INSERT INTO data (name, category) VALUES ('earrings', 'product');
INSERT INTO data (name, category) VALUES ('elastic', 'product');
INSERT INTO data (name, category) VALUES ('evening gown', 'product');
INSERT INTO data (name, category) VALUES ('fashion', 'product');
INSERT INTO data (name, category) VALUES ('fatigues', 'product');
INSERT INTO data (name, category) VALUES ('fez', 'product');
INSERT INTO data (name, category) VALUES ('flak jacket', 'product');
INSERT INTO data (name, category) VALUES ('flannel nightgown', 'product');
INSERT INTO data (name, category) VALUES ('flannel shirt', 'product');
INSERT INTO data (name, category) VALUES ('formal wear', 'product');
INSERT INTO data (name, category) VALUES ('frock', 'product');
INSERT INTO data (name, category) VALUES ('fur', 'product');
INSERT INTO data (name, category) VALUES ('fur coat', 'product');
INSERT INTO data (name, category) VALUES ('gabardine', 'product');
INSERT INTO data (name, category) VALUES ('gaiters', 'product');
INSERT INTO data (name, category) VALUES ('galoshes', 'product');
INSERT INTO data (name, category) VALUES ('garbgarment', 'product');
INSERT INTO data (name, category) VALUES ('garters', 'product');
INSERT INTO data (name, category) VALUES ('geargetup', 'product');
INSERT INTO data (name, category) VALUES ('gilet', 'product');
INSERT INTO data (name, category) VALUES ('girdle', 'product');
INSERT INTO data (name, category) VALUES ('glasses', 'product');
INSERT INTO data (name, category) VALUES ('gloves', 'product');
INSERT INTO data (name, category) VALUES ('gown', 'product');
INSERT INTO data (name, category) VALUES ('halter top', 'product');
INSERT INTO data (name, category) VALUES ('handbag', 'product');
INSERT INTO data (name, category) VALUES ('handkerchief', 'product');
INSERT INTO data (name, category) VALUES ('hat', 'product');
INSERT INTO data (name, category) VALUES ('Hawaiian shirt', 'product');
INSERT INTO data (name, category) VALUES ('hazmat suit', 'product');
INSERT INTO data (name, category) VALUES ('headscarf', 'product');
INSERT INTO data (name, category) VALUES ('helmet', 'product');
INSERT INTO data (name, category) VALUES ('hem', 'product');
INSERT INTO data (name, category) VALUES ('high heels', 'product');
INSERT INTO data (name, category) VALUES ('hoodie', 'product');
INSERT INTO data (name, category) VALUES ('hook and eye', 'product');
INSERT INTO data (name, category) VALUES ('hosehosiery', 'product');
INSERT INTO data (name, category) VALUES ('hospital gown', 'product');
INSERT INTO data (name, category) VALUES ('houndstooth', 'product');
INSERT INTO data (name, category) VALUES ('housecoat', 'product');
INSERT INTO data (name, category) VALUES ('jacket', 'product');
INSERT INTO data (name, category) VALUES ('jeans', 'product');
INSERT INTO data (name, category) VALUES ('jersey', 'product');
INSERT INTO data (name, category) VALUES ('jewelry', 'product');
INSERT INTO data (name, category) VALUES ('jodhpurs', 'product');
INSERT INTO data (name, category) VALUES ('jumper', 'product');
INSERT INTO data (name, category) VALUES ('jumpsuit', 'product');
INSERT INTO data (name, category) VALUES ('kerchief', 'product');
INSERT INTO data (name, category) VALUES ('khakis', 'product');
INSERT INTO data (name, category) VALUES ('kilt', 'product');
INSERT INTO data (name, category) VALUES ('kimono', 'product');
INSERT INTO data (name, category) VALUES ('kit', 'product');
INSERT INTO data (name, category) VALUES ('knickers', 'product');
INSERT INTO data (name, category) VALUES ('lab coat', 'product');
INSERT INTO data (name, category) VALUES ('lapel', 'product');
INSERT INTO data (name, category) VALUES ('leather jacket', 'product');
INSERT INTO data (name, category) VALUES ('leggings', 'product');
INSERT INTO data (name, category) VALUES ('leotard', 'product');
INSERT INTO data (name, category) VALUES ('life jacket', 'product');
INSERT INTO data (name, category) VALUES ('lingerie', 'product');
INSERT INTO data (name, category) VALUES ('loinc', 'product');
INSERT INTO data (name, category) VALUES ('lothlong johns', 'product');
INSERT INTO data (name, category) VALUES ('long underwear', 'product');
INSERT INTO data (name, category) VALUES ('miniskirt', 'product');
INSERT INTO data (name, category) VALUES ('mittens', 'product');
INSERT INTO data (name, category) VALUES ('muffler', 'product');
INSERT INTO data (name, category) VALUES ('muumuu', 'product');
INSERT INTO data (name, category) VALUES ('neckerchief', 'product');
INSERT INTO data (name, category) VALUES ('necklace', 'product');
INSERT INTO data (name, category) VALUES ('nightgown', 'product');
INSERT INTO data (name, category) VALUES ('nightshirt', 'product');
INSERT INTO data (name, category) VALUES ('onesies', 'product');
INSERT INTO data (name, category) VALUES ('outerwear', 'product');
INSERT INTO data (name, category) VALUES ('outfit', 'product');
INSERT INTO data (name, category) VALUES ('overalls', 'product');
INSERT INTO data (name, category) VALUES ('overcoat', 'product');
INSERT INTO data (name, category) VALUES ('overshirt', 'product');
INSERT INTO data (name, category) VALUES ('pajamas', 'product');
INSERT INTO data (name, category) VALUES ('panama hat', 'product');
INSERT INTO data (name, category) VALUES ('pants', 'product');
INSERT INTO data (name, category) VALUES ('pantsuit', 'product');
INSERT INTO data (name, category) VALUES ('pantyhose', 'product');
INSERT INTO data (name, category) VALUES ('parkapea coat', 'product');
INSERT INTO data (name, category) VALUES ('peplum', 'product');
INSERT INTO data (name, category) VALUES ('petticoat', 'product');
INSERT INTO data (name, category) VALUES ('pinafore', 'product');
INSERT INTO data (name, category) VALUES ('pleat', 'product');
INSERT INTO data (name, category) VALUES ('pocket', 'product');
INSERT INTO data (name, category) VALUES ('pocketbook', 'product');
INSERT INTO data (name, category) VALUES ('polo shirt', 'product');
INSERT INTO data (name, category) VALUES ('poncho', 'product');
INSERT INTO data (name, category) VALUES ('poodle skirt', 'product');
INSERT INTO data (name, category) VALUES ('pork pie hat', 'product');
INSERT INTO data (name, category) VALUES ('pullover', 'product');
INSERT INTO data (name, category) VALUES ('pumps', 'product');
INSERT INTO data (name, category) VALUES ('purse', 'product');
INSERT INTO data (name, category) VALUES ('raincoat', 'product');
INSERT INTO data (name, category) VALUES ('ring', 'product');
INSERT INTO data (name, category) VALUES ('robe', 'product');
INSERT INTO data (name, category) VALUES ('rugby shirt', 'product');
INSERT INTO data (name, category) VALUES ('sandals', 'product');
INSERT INTO data (name, category) VALUES ('sarisarong', 'product');
INSERT INTO data (name, category) VALUES ('scarf', 'product');
INSERT INTO data (name, category) VALUES ('school uniform', 'product');
INSERT INTO data (name, category) VALUES ('scrubs', 'product');
INSERT INTO data (name, category) VALUES ('shawl', 'product');
INSERT INTO data (name, category) VALUES ('sheath dress', 'product');
INSERT INTO data (name, category) VALUES ('shift', 'product');
INSERT INTO data (name, category) VALUES ('shirt', 'product');
INSERT INTO data (name, category) VALUES ('shoe', 'product');
INSERT INTO data (name, category) VALUES ('shorts', 'product');
INSERT INTO data (name, category) VALUES ('shoulder pads', 'product');
INSERT INTO data (name, category) VALUES ('shrug', 'product');
INSERT INTO data (name, category) VALUES ('singlet', 'product');
INSERT INTO data (name, category) VALUES ('skirt', 'product');
INSERT INTO data (name, category) VALUES ('slacks', 'product');
INSERT INTO data (name, category) VALUES ('slip', 'product');
INSERT INTO data (name, category) VALUES ('slippers', 'product');
INSERT INTO data (name, category) VALUES ('smock', 'product');
INSERT INTO data (name, category) VALUES ('snaps', 'product');
INSERT INTO data (name, category) VALUES ('sneakers', 'product');
INSERT INTO data (name, category) VALUES ('sock', 'product');
INSERT INTO data (name, category) VALUES ('sombrero', 'product');
INSERT INTO data (name, category) VALUES ('spacesuit', 'product');
INSERT INTO data (name, category) VALUES ('Stetson hat', 'product');
INSERT INTO data (name, category) VALUES ('stole', 'product');
INSERT INTO data (name, category) VALUES ('suit', 'product');
INSERT INTO data (name, category) VALUES ('sun hat', 'product');
INSERT INTO data (name, category) VALUES ('sunbonnet', 'product');
INSERT INTO data (name, category) VALUES ('sundress', 'product');
INSERT INTO data (name, category) VALUES ('sunglasses', 'product');
INSERT INTO data (name, category) VALUES ('suspenders', 'product');
INSERT INTO data (name, category) VALUES ('sweater', 'product');
INSERT INTO data (name, category) VALUES ('sweatpants', 'product');
INSERT INTO data (name, category) VALUES ('sweatshirt', 'product');
INSERT INTO data (name, category) VALUES ('sweatsuit', 'product');
INSERT INTO data (name, category) VALUES ('swimsuit', 'product');
INSERT INTO data (name, category) VALUES ('T-shirt', 'product');
INSERT INTO data (name, category) VALUES ('tam', 'product');
INSERT INTO data (name, category) VALUES ('tank top', 'product');
INSERT INTO data (name, category) VALUES ('teddy', 'product');
INSERT INTO data (name, category) VALUES ('threads', 'product');
INSERT INTO data (name, category) VALUES ('tiara', 'product');
INSERT INTO data (name, category) VALUES ('tie', 'product');
INSERT INTO data (name, category) VALUES ('tie clip', 'product');
INSERT INTO data (name, category) VALUES ('tights', 'product');
INSERT INTO data (name, category) VALUES ('toga', 'product');
INSERT INTO data (name, category) VALUES ('togs', 'product');
INSERT INTO data (name, category) VALUES ('top', 'product');
INSERT INTO data (name, category) VALUES ('top coat', 'product');
INSERT INTO data (name, category) VALUES ('top hat', 'product');
INSERT INTO data (name, category) VALUES ('train', 'product');
INSERT INTO data (name, category) VALUES ('trench coat', 'product');
INSERT INTO data (name, category) VALUES ('trousers', 'product');
INSERT INTO data (name, category) VALUES ('trunks', 'product');
INSERT INTO data (name, category) VALUES ('tube top', 'product');
INSERT INTO data (name, category) VALUES ('tunic', 'product');
INSERT INTO data (name, category) VALUES ('turban', 'product');
INSERT INTO data (name, category) VALUES ('turtleneck', 'product');
INSERT INTO data (name, category) VALUES ('turtleneck shirt', 'product');
INSERT INTO data (name, category) VALUES ('tutu', 'product');
INSERT INTO data (name, category) VALUES ('tux', 'product');
INSERT INTO data (name, category) VALUES ('tuxedo', 'product');
INSERT INTO data (name, category) VALUES ('tweed jacket', 'product');
INSERT INTO data (name, category) VALUES ('twill', 'product');
INSERT INTO data (name, category) VALUES ('twin set', 'product');
INSERT INTO data (name, category) VALUES ('umbrella', 'product');
INSERT INTO data (name, category) VALUES ('underclothes', 'product');
INSERT INTO data (name, category) VALUES ('undershirt', 'product');
INSERT INTO data (name, category) VALUES ('underwear', 'product');
INSERT INTO data (name, category) VALUES ('uniform', 'product');
INSERT INTO data (name, category) VALUES ('veil', 'product');
INSERT INTO data (name, category) VALUES ('Velcro', 'product');
INSERT INTO data (name, category) VALUES ('vest', 'product');
INSERT INTO data (name, category) VALUES ('vestments', 'product');
INSERT INTO data (name, category) VALUES ('visor', 'product');
INSERT INTO data (name, category) VALUES ('waders', 'product');
INSERT INTO data (name, category) VALUES ('waistcoat', 'product');
INSERT INTO data (name, category) VALUES ('wear', 'product');
INSERT INTO data (name, category) VALUES ('wedding gown', 'product');
INSERT INTO data (name, category) VALUES ('Wellingtons', 'product');
INSERT INTO data (name, category) VALUES ('wetsuit', 'product');
INSERT INTO data (name, category) VALUES ('white tie', 'product');
INSERT INTO data (name, category) VALUES ('wig', 'product');
INSERT INTO data (name, category) VALUES ('windbreaker', 'product');
INSERT INTO data (name, category) VALUES ('woolens', 'product');
INSERT INTO data (name, category) VALUES ('wrap', 'product');
INSERT INTO data (name, category) VALUES ('Scissors', 'product');
INSERT INTO data (name, category) VALUES ('Screw driver', 'product');
INSERT INTO data (name, category) VALUES ('Settee', 'product');
INSERT INTO data (name, category) VALUES ('Sheets', 'product');
INSERT INTO data (name, category) VALUES ('Shelf', 'product');
INSERT INTO data (name, category) VALUES ('Shirts', 'product');
INSERT INTO data (name, category) VALUES ('Smoke detector', 'product');
INSERT INTO data (name, category) VALUES ('Socks', 'product');
INSERT INTO data (name, category) VALUES ('Spoons', 'product');
INSERT INTO data (name, category) VALUES ('Suitcases', 'product');
INSERT INTO data (name, category) VALUES ('Supplies', 'product');
INSERT INTO data (name, category) VALUES ('Sweeper', 'product');
INSERT INTO data (name, category) VALUES ('Pans', 'product');
INSERT INTO data (name, category) VALUES ('Pants', 'product');
INSERT INTO data (name, category) VALUES ('Paper', 'product');
INSERT INTO data (name, category) VALUES ('Pen', 'product');
INSERT INTO data (name, category) VALUES ('Pencil', 'product');
INSERT INTO data (name, category) VALUES ('Phones', 'product');
INSERT INTO data (name, category) VALUES ('Pitcher', 'product');
INSERT INTO data (name, category) VALUES ('Plastic', 'product');
INSERT INTO data (name, category) VALUES ('plates', 'product');
INSERT INTO data (name, category) VALUES ('Plates', 'product');
INSERT INTO data (name, category) VALUES ('Pliers', 'product');
INSERT INTO data (name, category) VALUES ('Prescriptions', 'product');
INSERT INTO data (name, category) VALUES ('Calendar', 'product');
INSERT INTO data (name, category) VALUES ('Carpet', 'product');
INSERT INTO data (name, category) VALUES ('Chair', 'product');
INSERT INTO data (name, category) VALUES ('Clock', 'product');
INSERT INTO data (name, category) VALUES ('Coffee table', 'product');
INSERT INTO data (name, category) VALUES ('Comb', 'product');
INSERT INTO data (name, category) VALUES ('Containers', 'product');
INSERT INTO data (name, category) VALUES ('Credenza', 'product');
INSERT INTO data (name, category) VALUES ('Cup', 'product');
INSERT INTO data (name, category) VALUES ('Cushions', 'product');
INSERT INTO data (name, category) VALUES ('Backpack', 'product');
INSERT INTO data (name, category) VALUES ('Bedding', 'product');
INSERT INTO data (name, category) VALUES ('Bedspread', 'product');
INSERT INTO data (name, category) VALUES ('Binders', 'product');
INSERT INTO data (name, category) VALUES ('Blinds', 'product');
INSERT INTO data (name, category) VALUES ('Bookcase', 'product');
INSERT INTO data (name, category) VALUES ('yoke', 'product');
INSERT INTO data (name, category) VALUES ('zipperzoris', 'product');
INSERT INTO data (name, category) VALUES ('Air Purifier', 'product');
INSERT INTO data (name, category) VALUES ('Bachelor Griller', 'product');
INSERT INTO data (name, category) VALUES ('Backup Charger', 'product');
INSERT INTO data (name, category) VALUES ('Banknote Counter', 'product');
INSERT INTO data (name, category) VALUES ('Bluetooth Speaker', 'product');
INSERT INTO data (name, category) VALUES ('Bread Maker', 'product');
INSERT INTO data (name, category) VALUES ('Calculator', 'product');
INSERT INTO data (name, category) VALUES ('Car Toy', 'product');
INSERT INTO data (name, category) VALUES ('Copier', 'product');
INSERT INTO data (name, category) VALUES ('Crock-Pot', 'product');
INSERT INTO data (name, category) VALUES ('Curling Iron', 'product');
INSERT INTO data (name, category) VALUES ('Digital Camera', 'product');
INSERT INTO data (name, category) VALUES ('Doorbell Camera', 'product');
INSERT INTO data (name, category) VALUES ('Drill', 'product');
INSERT INTO data (name, category) VALUES ('Dvd Player', 'product');
INSERT INTO data (name, category) VALUES ('Earphones', 'product');
INSERT INTO data (name, category) VALUES ('Electric Fan', 'product');
INSERT INTO data (name, category) VALUES ('Electric Frying Pan', 'product');
INSERT INTO data (name, category) VALUES ('Electric Grill', 'product');
INSERT INTO data (name, category) VALUES ('Electric Guitar', 'product');
INSERT INTO data (name, category) VALUES ('Electric Pencil Sharpener', 'product');
INSERT INTO data (name, category) VALUES ('Electric Razor', 'product');
INSERT INTO data (name, category) VALUES ('Electric Stove', 'product');
INSERT INTO data (name, category) VALUES ('Evaporative Cooler', 'product');
INSERT INTO data (name, category) VALUES ('Exhaust Fan', 'product');
INSERT INTO data (name, category) VALUES ('External Hard Drive', 'product');
INSERT INTO data (name, category) VALUES ('Facial Cleansing Machine', 'product');
INSERT INTO data (name, category) VALUES ('Fax', 'product');
INSERT INTO data (name, category) VALUES ('Grandfather Clock', 'product');
INSERT INTO data (name, category) VALUES ('Hair Straightening Machine', 'product');
INSERT INTO data (name, category) VALUES ('Hair Trimmer', 'product');
INSERT INTO data (name, category) VALUES ('Headset', 'product');
INSERT INTO data (name, category) VALUES ('Inkjet Printer', 'product');
INSERT INTO data (name, category) VALUES ('iPod', 'product');
INSERT INTO data (name, category) VALUES ('Kettle', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen Hood', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen Scale', 'product');
INSERT INTO data (name, category) VALUES ('Lamp', 'product');
INSERT INTO data (name, category) VALUES ('Lantern', 'product');
INSERT INTO data (name, category) VALUES ('Laser Printer', 'product');
INSERT INTO data (name, category) VALUES ('Lawn Mower', 'product');
INSERT INTO data (name, category) VALUES ('Lift', 'product');
INSERT INTO data (name, category) VALUES ('Light Bulb', 'product');
INSERT INTO data (name, category) VALUES ('Meat Grinder', 'product');
INSERT INTO data (name, category) VALUES ('Microphone', 'product');
INSERT INTO data (name, category) VALUES ('Microwave', 'product');
INSERT INTO data (name, category) VALUES ('Mosquito Racket', 'product');
INSERT INTO data (name, category) VALUES ('Plotter', 'product');
INSERT INTO data (name, category) VALUES ('Printer', 'product');
INSERT INTO data (name, category) VALUES ('Projector', 'product');
INSERT INTO data (name, category) VALUES ('Radiator', 'product');
INSERT INTO data (name, category) VALUES ('Reading Lamp', 'product');
INSERT INTO data (name, category) VALUES ('Rice Cooker', 'product');
INSERT INTO data (name, category) VALUES ('Robotic Vacuum Cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Sandwich Maker', 'product');
INSERT INTO data (name, category) VALUES ('Scanner', 'product');
INSERT INTO data (name, category) VALUES ('Smartphone', 'product');
INSERT INTO data (name, category) VALUES ('Speaker', 'product');
INSERT INTO data (name, category) VALUES ('Stove', 'product');
INSERT INTO data (name, category) VALUES ('Table Fan', 'product');
INSERT INTO data (name, category) VALUES ('Transistor', 'product');
INSERT INTO data (name, category) VALUES ('Toaster', 'product');
INSERT INTO data (name, category) VALUES ('USB Drive', 'product');
INSERT INTO data (name, category) VALUES ('Walkie-Talkie', 'product');
INSERT INTO data (name, category) VALUES ('Water Pumps', 'product');
INSERT INTO data (name, category) VALUES ('Water Purifier', 'product');
INSERT INTO data (name, category) VALUES ('Webcam', 'product');
INSERT INTO data (name, category) VALUES ('Wifi Mod', 'product');
INSERT INTO data (name, category) VALUES ('Air purifier', 'product');
INSERT INTO data (name, category) VALUES ('Air conditioner', 'product');
INSERT INTO data (name, category) VALUES ('Alarm clock', 'product');
INSERT INTO data (name, category) VALUES ('Backup charger', 'product');
INSERT INTO data (name, category) VALUES ('Bread maker', 'product');
INSERT INTO data (name, category) VALUES ('Banknote counter', 'product');
INSERT INTO data (name, category) VALUES ('Bluetooth speaker', 'product');
INSERT INTO data (name, category) VALUES ('Bulb', 'product');
INSERT INTO data (name, category) VALUES ('Car toy', 'product');
INSERT INTO data (name, category) VALUES ('Ceiling fan', 'product');
INSERT INTO data (name, category) VALUES ('Clothes dryer', 'product');
INSERT INTO data (name, category) VALUES ('Coffee maker', 'product');
INSERT INTO data (name, category) VALUES ('Curling iron', 'product');
INSERT INTO data (name, category) VALUES ('Digital camera', 'product');
INSERT INTO data (name, category) VALUES ('Doorbell camera', 'product');
INSERT INTO data (name, category) VALUES ('Dvd player', 'product');
INSERT INTO data (name, category) VALUES ('Electric frying pan', 'product');
INSERT INTO data (name, category) VALUES ('Electric grill', 'product');
INSERT INTO data (name, category) VALUES ('Electric guitar', 'product');
INSERT INTO data (name, category) VALUES ('Electric pencil sharpener', 'product');
INSERT INTO data (name, category) VALUES ('Electric razor', 'product');
INSERT INTO data (name, category) VALUES ('Electric stove', 'product');
INSERT INTO data (name, category) VALUES ('Exhaust fan', 'product');
INSERT INTO data (name, category) VALUES ('External hard drive', 'product');
INSERT INTO data (name, category) VALUES ('Facial cleansing machine', 'product');
INSERT INTO data (name, category) VALUES ('Fish tank', 'product');
INSERT INTO data (name, category) VALUES ('Floor lamp', 'product');
INSERT INTO data (name, category) VALUES ('Game controller', 'product');
INSERT INTO data (name, category) VALUES ('Grandfather clock', 'product');
INSERT INTO data (name, category) VALUES ('Hair dryer', 'product');
INSERT INTO data (name, category) VALUES ('Inkjet printer', 'product');
INSERT INTO data (name, category) VALUES ('Kitchen scale', 'product');
INSERT INTO data (name, category) VALUES ('Hair straightening machine', 'product');
INSERT INTO data (name, category) VALUES ('Laser printer', 'product');
INSERT INTO data (name, category) VALUES ('Lawn mower', 'product');
INSERT INTO data (name, category) VALUES ('Meat grinder', 'product');
INSERT INTO data (name, category) VALUES ('Mosquito racket', 'product');
INSERT INTO data (name, category) VALUES ('Mp3 player', 'product');
INSERT INTO data (name, category) VALUES ('Oil-free fryer', 'product');
INSERT INTO data (name, category) VALUES ('Pressure cooker', 'product');
INSERT INTO data (name, category) VALUES ('Reading lamp', 'product');
INSERT INTO data (name, category) VALUES ('Remote control', 'product');
INSERT INTO data (name, category) VALUES ('Rice cooker', 'product');
INSERT INTO data (name, category) VALUES ('Robotic vacuum cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Sandwich maker', 'product');
INSERT INTO data (name, category) VALUES ('Scale', 'product');
INSERT INTO data (name, category) VALUES ('Sewing machine', 'product');
INSERT INTO data (name, category) VALUES ('Smart television', 'product');
INSERT INTO data (name, category) VALUES ('Tablet', 'product');
INSERT INTO data (name, category) VALUES ('USB drive', 'product');
INSERT INTO data (name, category) VALUES ('Vacuum cleaner', 'product');
INSERT INTO data (name, category) VALUES ('Walkie-talkie', 'product');
INSERT INTO data (name, category) VALUES ('Washing machine', 'product');
INSERT INTO data (name, category) VALUES ('Water pumps', 'product');
INSERT INTO data (name, category) VALUES ('Water purifier', 'product');
INSERT INTO data (name, category) VALUES ('Wall fan', 'product');
INSERT INTO data (name, category) VALUES ('Water heater', 'product');
